import React from 'react';
import Head from 'next/head';

interface IProps {}

const Header: React.FC<IProps> = () => {
  return (
    <Head>
      <title>Food Advisor</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
  );
};

export default Header;
